### ISSUE TITLE
kafka-http-connector v0.11 old common library version

### ISSUE THREAD

**Issue by Tri0L** [fission/keda-connectors#143]
For now kafka-http-connector (v0.11 docker image) use old version of common library.

https://github.com/fission/keda-connectors/blob/e282d4285f161adc64f44e936eae16061a0a2f56/kafka-http-connector/go.mod#L7

Meta version of this commit https://github.com/fission/keda-connectors/commit/da094250dc08
This version have a bug with response code processing.

https://github.com/fission/keda-connectors/blob/da094250dc08122358a725cf67d54cf5fc313396/common/util.go#L94

Because of this, error messages are never sent to the error topic.

Related issue in fission: https://github.com/fission/fission/issues/2739

**Comment by sanketsudake** [comment]
Should be resolved via https://github.com/fission/keda-connectors/pull/158

Please try latest version of package https://github.com/fission/keda-connectors/pkgs/container/keda-kafka-http-connector/150999247?tag=v0.13
