### ISSUE TITLE
[Bug] Duplicated content type in header when use kafka-http-connector

### ISSUE THREAD

**Issue by chenjr0719** [fission/keda-connectors#45]
Hi there, I found an issue in kafka-http-connector.
https://github.com/fission/keda-connectors/blob/da094250dc08122358a725cf67d54cf5fc313396/kafka-http-connector/main.go#L215-L226

If the message header also specifies the same keys (ex: content-type), when it sends the request to the function might be broken because of the duplicate key.

I would like to know, is it possible to check the message header first, and if it doesn't contain the same key, we use the default value here?

**Comment by blackfly19** [comment]
Hi @chenjr0719. Can you please provide the steps to reproduce the issue?

**Comment by soharab-ic** [comment]
@chenjr0719 `http.Header` is of type `map[string][]string`. It can have a slice of values for every key. The `Add` method does not overwrite existing values, it appends new values to the slice associated with the key.
