### ISSUE TITLE
AWS SQS Connector failed to get environment variable

### ISSUE THREAD

**Issue by AnthraX1** [fission/keda-connectors#46]
I'm following the docs at https://docs.fission.io/docs/triggers/message-queue-trigger-kind-keda/aws-sqs/ . I've setup  kubectl secrets per instruction and ran `fission mqt create  --name sqstest --function sqstest --mqtype=aws-sqs-queue --topic=fission-test --mqtkind=keda --metadata queueURL=https://sqs.us-west-2.amazonaws.com/xxxxx/fission-test --metadata awsRegion=us-west-2 --secret aws-secret` to create the trigger. However, the connector pod won't start correctly:

kubectl get pods -A

...
`default            sqstest-7d6fc4d78c-whq4w                                 0/1     CrashLoopBackOff   1          11s`
...

kubectl logs sqstest-7d6fc4d78c-whq4w

`{"level":"error","ts":1609595317.8034132,"caller":"app/main.go:201","msg":"failed to fetch aws config","error":"no aws configuration specified","stacktrace":"main.main\n\t/app/main.go:201\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}`

kubectl get pod sqstest-7568bc9cbd-c7gjd -o json

`....
   "spec": {
        "containers": [
            {
                "env": [
                    {
                        "name": "TOPIC",
                        "value": "fission-test"
                    },
                    {
                        "name": "HTTP_ENDPOINT",
                        "value": "http://router.fission/fission-function/sqstest"
                    },
                    {
                        "name": "ERROR_TOPIC"
                    },
                    {
                        "name": "RESPONSE_TOPIC"
                    },
                    {
                        "name": "SOURCE_NAME",
                        "value": "sqstest"
                    },
                    {
                        "name": "MAX_RETRIES",
                        "value": "0"
                    },
                    {
                        "name": "CONTENT_TYPE",
                        "value": "application/json"
                    },
                    {
                        "name": "AWS_REGION",
                        "value": "us-west-2"
                    },
                    {
                        "name": "QUEUE_URL",
                        "value": "https://sqs.us-west-2.amazonaws.com/xxxxxxxxx/fission-test"
                    },
                    {
                        "name": "AWS_ACCESS_KEY_ID",
                        "value": "xxxxxxxxxxxxx"
                    },
                    {
                        "name": "AWS_SECRET_ACCESS_KEY",
                        "value": "xxxxxxxxxxxxx"
                    }
                ],
                "image": "fission/keda-aws-sqs-http-connector:1",
....
`

From the pod env you can see the access keys are correctly set but the pod still crashes with the same error.

**Comment by AnthraX1** [comment]
OK, seems the image on dockerhub is behind:
https://hub.docker.com/r/fission/keda-aws-sqs-http-connector/ is using commit before https://github.com/fission/keda-connectors/commit/79b8796b854f5699ed2ce71d1dfa8ba51a8175c9

**Comment by jry-anchor** [comment]
I edited the deployment for the sqs connector pod -- for me in the default ns pod `deployment.apps/<trigger name>` -- to use the old env var names and it runs now. Who knows if that will be reverted though, since fission somehow owns that deployment

**Comment by jry-anchor** [comment]
https://github.com/jry-anchor/keda-connectors/commit/1b0c6cb624a1a5622bba95e39876aa05ff4b5833 would be an easy fix without waiting for a fission release if we could get someone to update the `fission/keda-aws-sqs-http-connector:1` docker image tag in-place. I assume c68eb4e4d was the source of that build, so my commit is on top of it.

**Comment by soharab-ic** [comment]
Please try latest version of keda-aws-sqs-http-connector https://github.com/fission/keda-connectors/pkgs/container/keda-aws-sqs-http-connector/279693262?tag=v0.16.
