### ISSUE TITLE
Integration test for connectors

### ISSUE THREAD

**Issue by vishal-biyani** [fission/keda-connectors#7]
A generic integration test framework for Keda connectors which can simulate:

1. Create a Kind cluster
2. Deploy the respective MQ (For PR - detect changes to specific connector dynamically)
3. Deploy the mq-keda-connector deployment
4. A simple HTTP server which can listen for messages
5. Drop a message in source topic, expect a response in (4) server and response topic
6. Bring down the server in (4) and expect a response in error topic

Specific Tests for: 

- [ ] Kafka-http-connector
- [ ] RabbitMQ-http-connector

Recommend using Github workflow for end to end cycle.

**Comment by vishal-biyani** [comment]
- [ ] Our initial thought was to probably decouple the testing of connectors from Fission - while that is good, it seems that it might make it easy for us to Fission instead of writing all custom logic in docker images. Evaluate this and potentially use Fission in the integration test
- [ ] Currently the integration test only caters to SQS, Kafka and RabbitMQ, we need to add tests for others
- [ ] The release process needs a workflow - basically when a new PR is merged for a specific connector - the version should be bumped and pushed to Dockerhub and also tagged to be latest. The version number can be maintained as a file inside each connector directory and should be updated by person who raises the PR

**Comment by soharab-ic** [comment]
All objectives have been achieved and respective PR https://github.com/fission/keda-connectors/pull/61 has been merged.
Hence, closing the issue.
